name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to AWS Instance
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.18.183.71.54 }}
          username: ${{ secrets.ubuntu }}
          key: ${{ secrets.ssh -i "hospital.pem" ubuntu@ec2-18-183-71-54.ap-northeast-1.compute.amazonaws.com }}
          script: |
            cd /var/www/html
            git pull
            composer install
            sudo systemctl restart apache2
